import { NextRequest, NextResponse } from "next/server";
import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, resolve } from "node:path";
import { existsSync } from "node:fs";
import { spawn } from "node:child_process";

const rootDir = resolve(process.cwd());
const workDir = join(rootDir, ".worker", "lol");
const modelsDir = join(rootDir, "public", "models", "lol");

function resolveBlenderPath(): string {
  if (process.env.BLENDER_PATH && existsSync(process.env.BLENDER_PATH)) {
    return process.env.BLENDER_PATH;
  }
  const defaultWin51 = "C:\\Program Files\\Blender Foundation\\Blender 5.1\\blender.exe";
  if (existsSync(defaultWin51)) return defaultWin51;
  const defaultWin43 = "C:\\Program Files\\Blender Foundation\\Blender 4.3\\blender.exe";
  if (existsSync(defaultWin43)) return defaultWin43;
  return process.env.BLENDER_PATH ?? "blender";
}

const blenderPath = resolveBlenderPath();

function runBlender(scriptPath: string): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const proc = spawn(blenderPath, ["--background", "--python", scriptPath], { timeout: 900_000 });
    let stdout = "";
    let stderr = "";

    proc.stdout.on("data", (chunk) => { stdout += chunk.toString(); });
    proc.stderr.on("data", (chunk) => { stderr += chunk.toString(); });

    proc.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
      } else {
        reject(new Error(`Blender exited with code ${code}\nSTDERR:\n${stderr.slice(-1000)}`));
      }
    });

    proc.on("error", (err) => {
      reject(new Error(`Could not start Blender: ${err.message}`));
    });
  });
}

function parseScriptMetadata(filename: string, content: string, fileMtime: Date) {
  const lines = content.split("\n");

  // Extract dynamic code block (between try: and except Exception:)
  let dynamicCode = "";
  const tryIndex = lines.findIndex((l) => l.trim() === "try:");
  const exceptIndex = lines.findIndex((l) => l.trim().startsWith("except Exception"));

  if (tryIndex !== -1 && exceptIndex !== -1 && exceptIndex > tryIndex) {
    dynamicCode = lines
      .slice(tryIndex + 1, exceptIndex)
      .map((l) => (l.startsWith("    ") ? l.slice(4) : l))
      .join("\n")
      .trim();
  } else {
    dynamicCode = content;
  }

  // Find meaningful comment lines
  const descriptiveComments = lines
    .map((l) => l.trim())
    .filter(
      (l) =>
        l.startsWith("#") &&
        !l.includes("Clear default") &&
        !l.includes("Import original") &&
        !l.includes("Execute Agentic") &&
        !l.includes("Export modified") &&
        !l.includes("Procedural helper") &&
        !l.includes("=== AGENTIC")
    )
    .map((l) => l.replace(/^#+/, "").replace(/^[\s─\-_*#]+|[\s─\-_*#]+$/g, "").trim())
    .filter((l) => l.length > 3);

  let title = "Custom 3D Transformation";
  let summary = descriptiveComments.join(". ");

  if (filename.includes("test_script")) {
    title = "Demon Obsidian Horns & Wings";
    summary = "Sculpts 3D demonic obsidian horns on head and pairs with rigged obsidian wings.";
  } else if (descriptiveComments.length > 0) {
    title = descriptiveComments[0];
    if (descriptiveComments.length > 1) {
      summary = descriptiveComments.slice(0, 3).join(". ");
    }
  }

  // Fallbacks for well-known scripts if comment is generic
  if (title.toLowerCase().includes("shaders")) {
    if (content.includes("0.95, 0.3, 1.0")) {
      title = "Toxic Neon Green Metallic Shaders";
      summary = "High-metallic, low-roughness shaders with radioactive toxic green emission on Body, Sword, and Shoulder.";
    } else {
      title = "Procedural PBR Shader Overhaul";
    }
  }

  // Extract timestamp from filename or stat
  const match = filename.match(/(\d{13})/);
  const timestamp = match ? parseInt(match[1], 10) : fileMtime.getTime();

  const isCached = existsSync(join(modelsDir, "cache", `${filename.replace(/\.py$/, "")}.glb`));

  return {
    id: filename.replace(/\.py$/, ""),
    filename,
    title,
    summary: summary || "Procedural 3D model transformation generated by Agentic 3D engine.",
    timestamp,
    isCached,
    dateFormatted: new Date(timestamp).toLocaleString("en-GB", {
      day: "numeric",
      month: "short",
      hour: "2-digit",
      minute: "2-digit",
    }),
    dynamicCode,
    fullCode: content,
    lineCount: lines.length,
  };
}

export async function GET() {
  try {
    if (!existsSync(workDir)) {
      return NextResponse.json({ history: [] });
    }

    const files = await readdir(workDir);
    const pyFiles = files.filter((f) => f.endsWith(".py"));

    const historyItems = await Promise.all(
      pyFiles.map(async (file) => {
        const filePath = join(workDir, file);
        const fileStat = await stat(filePath);
        const content = await readFile(filePath, "utf-8");
        return parseScriptMetadata(file, content, fileStat.mtime);
      })
    );

    // Sort newest first
    historyItems.sort((a, b) => b.timestamp - a.timestamp);

    return NextResponse.json({ history: historyItems });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const { filename, championId = "aatrox" } = await req.json();

    if (!filename) {
      return NextResponse.json({ error: "Missing filename" }, { status: 400 });
    }

    const scriptPath = join(workDir, filename);
    if (!existsSync(scriptPath)) {
      return NextResponse.json({ error: `Script not found: ${filename}` }, { status: 404 });
    }

    const inputGlb = join(modelsDir, `${championId}.glb`);
    const backupCandidates = [
      join(rootDir, "..", `${championId}.glb`),
      join(rootDir, `${championId}.glb`),
      join(modelsDir, `${championId}_backup.glb`),
    ];

    const backupGlb = backupCandidates.find((p) => existsSync(p));
    if (!backupGlb) {
      return NextResponse.json({ error: `Pristine baseline backup model not found for ${championId}` }, { status: 404 });
    }

    const cacheDir = join(modelsDir, "cache");
    const cachedGlb = join(cacheDir, `${filename.replace(/\.py$/, "")}.glb`);

    // If already pre-rendered, copy instantly in 10ms!
    if (existsSync(cachedGlb)) {
      await writeFile(inputGlb, await readFile(cachedGlb));
      return NextResponse.json({
        success: true,
        message: `Instantly loaded cached 3D model '${filename}'!`,
        updated: true,
        fromCache: true,
      });
    }

    // Reset to baseline first so this transformation applies cleanly
    await writeFile(inputGlb, await readFile(backupGlb));

    // Run the selected script in Blender
    await runBlender(scriptPath);

    // Save to cache for instant future loads
    try {
      await writeFile(cachedGlb, await readFile(inputGlb));
    } catch {}

    return NextResponse.json({
      success: true,
      message: `Successfully rendered transformation '${filename}' with Blender!`,
      updated: true,
      fromCache: false,
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
